services:
  flask-api:
    build:
      context: ./bookstore_api
    container_name: flask-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - MONGO_URI=mongodb+srv://vaued2025a2g09:oaTsa6H61PZlE3cb@cluster0.l50ynzo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  node_exporter:
    image: prom/node-exporter:latest
    pid: host
    volumes:
      - "/:/host:ro"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "5000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
