global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: [node_exporter:9100]

  - job_name: flask-api
    metrics_path: /metrics
    static_configs:
      - targets: [flask-api:8080]
