global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-api'
    metrics_path: /metrics  # ensure your Flask app has this route
    scheme: https
    static_configs:
      - targets:
          - 'bookstore-dna2hmc7egf4ewc9.canadacentral-01.azurewebsites.net'
